# Generated by Django 2.1.7 on 2019-02-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=30)),
                ('No_registro', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_recibido', models.DateField()),
            ],
        ),
    ]
