# Generated by Django 2.1.7 on 2019-04-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=30)),
                ('fecha_recibido', models.DateField()),
                ('cliente', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
