# Generated by Django 2.1.7 on 2019-03-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20190318_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=60)),
                ('domicilio', models.CharField(max_length=70)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
