# Generated by Django 2.1.7 on 2019-03-22 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('fecha_recibido', models.DateField()),
                ('No_reporte', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.BigIntegerField()),
                ('equipo_recibido', models.CharField(max_length=30)),
                ('falla_reportada', models.CharField(max_length=40)),
                ('trabajo_realizado', models.CharField(max_length=80)),
                ('observaciones', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('atendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Empleados')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
            ],
        ),
    ]
