# Generated by Django 2.1.7 on 2019-03-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('fecha_recibido', models.DateField()),
                ('No_reporte', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('equipo_recibido', models.CharField(max_length=30)),
                ('falla_reportada', models.CharField(max_length=40)),
                ('trabajo_realizado', models.CharField(max_length=80)),
                ('observaciones', models.CharField(max_length=30)),
                ('atendido', models.ManyToManyField(to='reportes.Empleados')),
            ],
        ),
    ]
