# Generated by Django 2.1.7 on 2019-04-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recibido', models.DateField()),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('equipo_recibido', models.CharField(max_length=30)),
                ('falla_reportada', models.CharField(max_length=40)),
                ('trabajo_realizado', models.CharField(max_length=80)),
                ('observaciones', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('atendido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Empleados')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Clientes')),
                ('realizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Lugar')),
            ],
        ),
    ]
