# Generated by Django 2.1.7 on 2019-03-22 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_lugar'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='realizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Lugar'),
        ),
    ]
