# Generated by Django 2.1.7 on 2019-02-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='atendido',
        ),
        migrations.AddField(
            model_name='reportes',
            name='atendido',
            field=models.ManyToManyField(blank=True, to='reportes.Empleados'),
        ),
    ]
