# Generated by Django 2.1.7 on 2019-04-02 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='fecha_recibido',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 1, 19, 49, 4, 939249)),
        ),
    ]
