# Generated by Django 2.1.7 on 2019-02-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20190219_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='atendido',
        ),
    ]
