# Generated by Django 2.1.7 on 2019-04-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_auto_20190401_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='fecha_recibido',
            field=models.DateField(),
        ),
    ]
