# Generated by Django 2.1.7 on 2019-02-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_reportes_atendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='atendido',
            field=models.ManyToManyField(blank=True, to='reportes.Empleados'),
        ),
    ]
