# Generated by Django 2.1.7 on 2019-02-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_reportes_atendido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='telefono',
        ),
    ]
