# Generated by Django 2.1.7 on 2019-02-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_remove_reportes_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='telefono',
            field=models.IntegerField(default=4445),
            preserve_default=False,
        ),
    ]
